import { ArrowRight, CupSoda, Leaf, Utensils } from "lucide-react";
import { ActionLink } from "@/components/ui/Buttons";
import { EditorialCard } from "@/components/ui/EditorialCard";
import { Media } from "@/components/ui/Media";
import { PageHero } from "@/components/ui/PageHero";
import { Reveal } from "@/components/ui/Reveal";
import { SectionLabel } from "@/components/ui/Section";
import { images, mapLink, wazeLink } from "@/data/site";

export default function RestaurantPage() { return <main><PageHero eyebrow="FFC Restaurant" title={<>Real Ingredients.<br />Food Made With Care.</>} copy="Come experience what FFC believes in through a tea bar and comforting home-style cooking." image={images.dish}><div className="hero-actions"><ActionLink href="/restaurant/menu">Explore Menu <ArrowRight /></ActionLink><ActionLink href="#visit" variant="ghost">Visit Us <ArrowRight /></ActionLink></div></PageHero><section className="section discovery-section"><div className="shell"><Reveal><SectionLabel>Explore FFC Restaurant</SectionLabel><h2>From menu to kitchen,<br />it all matters.</h2></Reveal><div className="discovery-grid"><Reveal><EditorialCard href="/restaurant/menu" image={images.dish} title="Menu" copy="Explore our tea bar, home-style dishes and signature creations." /></Reveal><Reveal delay={.1}><EditorialCard href="/restaurant/kitchen" image={images.kitchen} title="Our Kitchen" copy="Discover how thoughtful preparation lets ingredients speak for themselves." /></Reveal><Reveal delay={.2}><EditorialCard href="/restaurant/ingredients" image={images.greens} title="Our Ingredients" copy="Learn how ingredient choices shape everything we serve." /></Reveal></div></div></section><section className="section restaurant-philosophy"><div className="shell split"><Reveal><SectionLabel>Our Philosophy</SectionLabel><h2>From ingredient<br />to table.</h2><p className="body-copy">A simple food experience shaped by care, comfort and thoughtful choices.</p></Reveal><Reveal className="point-list" delay={.1}><span><Leaf /><b>Thoughtful Ingredients</b><small>Ingredient choices lead the way.</small></span><span><Utensils /><b>Home-style Cooking</b><small>Comfort made with care.</small></span><span><CupSoda /><b>Tea &amp; Original Creations</b><small>Small rituals worth sharing.</small></span></Reveal></div></section><section className="section visit-section" id="visit"><div className="shell split"><Reveal><Media src={images.restaurant} alt="FFC restaurant interior placeholder" className="visit-photo" /></Reveal><Reveal><SectionLabel>Visit Our Restaurant</SectionLabel><h2>Come experience it<br />at our table.</h2><p className="visit-name">Foodie &amp; Friend Cuisine</p><address>1st Floor, 1D-1,<br />Jalan SS 9a/17,<br />43700 Petaling Jaya,<br />Selangor</address><div className="hero-actions"><a className="button button-primary" target="_blank" rel="noreferrer" href={mapLink}>Google Maps <ArrowRight /></a><a className="button button-ghost" target="_blank" rel="noreferrer" href={wazeLink}>Waze <ArrowRight /></a></div></Reveal></div></section></main>; }
