import { ArrowRight, Leaf, Sun, UsersRound, type LucideIcon } from "lucide-react";
import { ActionLink } from "@/components/ui/Buttons";
import { Media } from "@/components/ui/Media";
import { PageHero } from "@/components/ui/PageHero";
import { Reveal } from "@/components/ui/Reveal";
import { SectionLabel } from "@/components/ui/Section";
import { images } from "@/data/site";

const values: Array<[LucideIcon, string, string]> = [[Leaf, "Real Ingredients", "Food as it should be."], [UsersRound, "Responsible Practices", "For people and the planet."], [UsersRound, "Stronger Communities", "Good food brings people together."], [Sun, "A Better Tomorrow", "Healthier food, brighter futures."]];
export default function AboutPage() { return <main><PageHero eyebrow="About Us" title={<>People,<br />Ingredients,<br />A Better Tomorrow.</>} copy="Foodie &amp; Friend Cuisine brings together people who believe better food begins with real ingredients." image={images.salad} /><section className="section about-story"><div className="shell split"><Reveal><Media src={images.greens} alt="Fresh ingredient basket placeholder" className="story-image" /></Reveal><Reveal><SectionLabel>Our Story</SectionLabel><h2>A community built<br />around honest food.</h2><p className="body-copy">We connect food makers, restaurants, cooks and producers who care about real ingredients and healthier, more sustainable food for future generations.</p><ActionLink href="/contact" variant="text">Our Journey <ArrowRight /></ActionLink><p className="story-tagline">Real Ingredients.<br />Real People.</p></Reveal></div></section><section className="section value-section"><div className="shell"><Reveal><SectionLabel>Our Values</SectionLabel><h2>What we stand for.</h2></Reveal><div className="value-grid">{values.map(([Icon, title, copy]) => <Reveal className="value-item" key={title}><span className="icon-orb"><Icon /></span><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></div></section><section className="founders-section"><Media src={images.restaurant} alt="Warm dining room placeholder" /><div className="shell founders-copy"><Reveal><SectionLabel>Our Founders</SectionLabel><h2>Food brings<br />us together.</h2><p>Founded by Mr. Foong &amp; Queen Chin, who share a simple belief — good food can create a better tomorrow.</p><ActionLink href="/contact" variant="text">Meet Our Founders <ArrowRight /></ActionLink></Reveal></div></section><section className="about-close"><div className="shell"><div><h2>Better ingredients.<br />Brighter tomorrows.</h2></div><ActionLink href="/contact">Get FFC Certified <ArrowRight /></ActionLink></div></section></main>; }
