"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, LoaderCircle } from "lucide-react";

const initial = { name: "", company: "", country: "", state: "", phone: "", email: "", enquiry: "", message: "" };
export function ContactForm() {
  const [values, setValues] = useState(initial); const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle"); const [error, setError] = useState("");
  const update = (key: keyof typeof initial, value: string) => setValues((prev) => ({ ...prev, [key]: value }));
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); if (!values.name || !values.company || !values.country || !values.state || !values.phone || !values.enquiry || !values.message) { setState("error"); setError("Please complete the required fields before sending your enquiry."); return; } setState("loading"); window.setTimeout(() => setState("success"), 650); };
  if (state === "success") return <div className="form-success"><CheckCircle2 /><h3>Thank you for reaching out.</h3><p>Your message is ready for the FFC team. This demo form does not send data until an API is configured.</p><button onClick={() => { setValues(initial); setState("idle"); }}>Send another message</button></div>;
  return <form className="contact-form" onSubmit={submit} noValidate><div className="form-grid"><label>Person In-charge Name *<input value={values.name} onChange={(e) => update("name", e.target.value)} /></label><label>Company Name *<input value={values.company} onChange={(e) => update("company", e.target.value)} /></label><label>Country *<input value={values.country} onChange={(e) => update("country", e.target.value)} /></label><label>State *<input value={values.state} onChange={(e) => update("state", e.target.value)} /></label><label>Contact Number *<input value={values.phone} onChange={(e) => update("phone", e.target.value)} placeholder="Malaysia +60" /></label><label>Email<input type="email" value={values.email} onChange={(e) => update("email", e.target.value)} /></label></div><label>Enquiry Type *<select value={values.enquiry} onChange={(e) => update("enquiry", e.target.value)}><option value="">Select an enquiry type</option><option>FFC Certification</option><option>Restaurant</option><option>Ingredient / Supply</option><option>Collaboration</option><option>General Enquiry</option></select></label><label>Message *<textarea rows={5} value={values.message} onChange={(e) => update("message", e.target.value)} /></label>{state === "error" && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary form-submit" disabled={state === "loading"}>{state === "loading" ? <><LoaderCircle className="spin" /> Preparing…</> : <>Send Message <ArrowRight /></>}</button><p className="form-note">This form is ready for API integration. No contact details are sent from this demo.</p></form>;
}
